title: Commerford Lineage
description: a website compiling all genealogical information
show_downloads: true

github:
  zip_url: https://cgreposit.github.io/genealogysite/family-directory.html
  tar_url: https://www.familyecho.com/?c=6btn6ba8y0y3ox84&f=195144334703685164

google_analytics: # optional tracking ID
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-remote-theme
